### PR TITLE
Add Button for CookbookViewCommand and fix bugs

### LINKED ISSUE #150: Tags in recipe in wrong order
`recipe add .... t/This t/is t/a t/tag` shows tags as `[tag] [This] [s] [a]` instead of `[This] [is] [a] [tag]`

### LINKED ISSUE #182: [PE-D] Ability to remove more ingredients than what I currently have
I am able to remove more ingredients than what I currently have.
In this case, I have 113 eggs, but I am able to remove 200 eggs from my ingredient list.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: JeremyLoh/ped#6

### PR DESCRIPTION
**Pull request by teo-jun-xiong**
image

- Add Button for CookbookViewCommand (executing the command now expands the recipe in the recipes panel)
- Add TagComparator to sort the tags alphabetically
- Modify CookbookAddCommand message to `New recipe (index INDEX) added: RECIPE_NAME`
- Fix Inventory and CartRemoveIngredientCommand to display the correct quantities of the removed ingredient

### CODE REVIEW

**Review by gohkh — APPROVED** [review]
Looks good, thanks!

**Review by hans555 — APPROVED** [review]

**Comment by gohkh** [comment]
I think the font for the "Your recipe/inventory/cart" is a little hard to read. For the header of the ingredient lists, maybe we can do away with the "#", as the numbers seem quite self-explanatory?

**Comment by gohkh** [comment]
Also, for some reason, the v1.3 app has problems with the UI on linux, even though the v1.2.1 jar file works fine. It looks like this:
image

**Comment by teo-jun-xiong** [comment]
> Also, for some reason, the v1.3 app has problems with the UI on linux, even though the v1.2.1 jar file works fine. It looks like this:
> image

Is this from downloading the .jar or by running it from IDE?

**Comment by gohkh** [comment]
> > Also, for some reason, the v1.3 app has problems with the UI on linux, even though the v1.2.1 jar file works fine. It looks like this:
> > image
> 
> Is this from downloading the .jar or by running it from IDE?

Both, not sure why

**Comment by teo-jun-xiong** [comment]
> Both, not sure why

Do you think you can fix it from your side? I think it might be a something to do with Linux since it seems to be fine on MacOS and Windows.  I'm not sure how serious this would be, but it would likely affect your progress?

**Comment by gohkh** [comment]
> > Both, not sure why
> 
> Do you think you can fix it from your side? I think it might be a something to do with Linux since it seems to be fine on MacOS and Windows. I'm not sure how serious this would be, but it would likely affect your progress?

I can work on windows too. Not sure if I can fix it but I can try :/ Somebody reported this as an issue during the PE dry run too. I can't find any similar problem online.

**Comment by teo-jun-xiong** [comment]
> > > Both, not sure why
> > 
> > 
> > Do you think you can fix it from your side? I think it might be a something to do with Linux since it seems to be fine on MacOS and Windows. I'm not sure how serious this would be, but it would likely affect your progress?
> 
> I can work on windows too. Not sure if I can fix it but I can try :/ Somebody reported this as an issue during the PE dry run too. I can't find any similar problem online.

I'll look through my code and see if I added anything out of the ordinary

**Review by shanecsj — APPROVED** [review]
If we are going ahead with this title font, I think we can simply remove the 'Your' from all the headings. Otherwise, LGTM!

**Pull request merged**
